<script setup lang="ts">
import Container from '@/game-components/board/Container.vue';
import { tilePath } from '@/game-components/board/Layout';
import SideMenu from '@/misc/SideMenu.vue';
import ErrorText from '@/modals/input-fields/ErrorText.vue';
import ErrorImg from '@/modals/input-fields/ErrorImg.vue';
import InputGroup from '@/modals/input-fields/InputGroup.vue';
import IntegerInput from '@/modals/input-fields/IntegerInput.vue';
import LabeledInput from '@/modals/input-fields/LabeledInput.vue';
import { type Coordinate, defaultScenario, type Distribution, GenerationMethod, sameCoordinate, type Scenario, ScenarioRobberPlacement, ScenarioStartingPhaseType, sumDistribution, TileType } from 'catan-shared';
import { computed, ref } from 'vue';
import Setting from '@/room/Setting.vue';
import FixedSelectionList from '@/modals/input-fields/FixedSelectionList.vue';

const minAllowedCount = ref<number | undefined>(1)
const maxAllowedCount = ref<number | undefined>(4)
const startingPhase   = ref<ScenarioStartingPhaseType.WithInitialPlacing>(ScenarioStartingPhaseType.WithInitialPlacing)
const robberPlacement = ref<ScenarioRobberPlacement.RandomDesert>(ScenarioRobberPlacement.RandomDesert)

const playersValid = computed(() => {
    if (minAllowedCount.value == undefined || maxAllowedCount.value == undefined)
        return false
    if (minAllowedCount.value > maxAllowedCount.value)
        return "Minimum has to be less than maximum"
    return true
})

type TileTypesGroupInfo = {
    method: GenerationMethod.Fixed | GenerationMethod.Distribution
    fixed: TileType[]
    distribution: Distribution<TileType>
}
function tileTypesCurrentLen(tt: TileTypesGroupInfo): number {
    if (tt.method == GenerationMethod.Fixed)
        return tt.fixed.length
    else
        return sumDistribution(tt.distribution)
}

type GroupInfo = {
    name: string
    coordinates: readonly (readonly Coordinate[])[]
    tileTypes: TileTypesGroupInfo
}

function groupsFromScenario(scenario: Scenario): GroupInfo[] {
    return scenario.board.tileGroups.map((group, idx) => {
        return {
            name: String(idx + 1),
            coordinates: group.coordinates.data,
            tileTypes: {
                method: group.tileTypes.method,
                fixed: group.tileTypes.method == GenerationMethod.Fixed ? group.tileTypes.data.slice() : [],
                distribution: group.tileTypes.method == GenerationMethod.Distribution ? group.tileTypes.data : {
                    [TileType.Desert]: 0,
                    [TileType.Resource]: 0,
                    [TileType.Port]: 0,
                    [TileType.Ocean]: 0
                }
            }
        }
    })
}

const tileGroups      = ref(groupsFromScenario(defaultScenario))
// rename groups for default scenario:
tileGroups.value[0].name = "Sea"
tileGroups.value[1].name = "Land"
const activeTileGroup = ref(tileGroups.value[0])
const activeCoord     = ref(activeTileGroup.value.coordinates[0][0])

function mostTiles(coords: readonly (readonly Coordinate[])[]): number {
    return coords.map(x => x.length).reduce((s, v) => s > v ? s : v, 0)
}
function tileGroupValid(gi : GroupInfo) {
    if (tileTypesCurrentLen(gi.tileTypes) < mostTiles(gi.coordinates)) {
            return 'Too few tiles'
    }

    return true
}
const tileGroupsValid = computed(() => tileGroups.value.every(x => tileGroupValid(x) === true))
const scenarioValid = computed(() => {
    return playersValid.value == true && tileGroupsValid.value == true
})

const activeTileGroupInfo = computed(() => {
    // Providing count refers to the number of tiles generated by this tile group
    // specified by the lower and upper bound
    let providingCount: [number, number]
    if (activeTileGroup.value.coordinates.length == 0)
        providingCount = [0, 0]
    else
        providingCount = [activeTileGroup.value.coordinates.map(x => x.length).sort()[0], 
                          activeTileGroup.value.coordinates.map(x => x.length).sort()[activeTileGroup.value.coordinates.length - 1]]

    return { providingCount }
})
const activeCoordInfo = computed(() => {
    const providingGroups = tileGroups.value.filter(tg => tg.coordinates.some(arr => arr.some(x => sameCoordinate(x, activeCoord.value))))
    return { providingGroups }
})



function appendEmptyTileGroup() {
    // TODO fix names
    tileGroups.value.push({
        coordinates: [],
        tileTypes: {
            method: GenerationMethod.Fixed,
            fixed: [],
            distribution: {
                [TileType.Desert]: 0,
                [TileType.Resource]: 0,
                [TileType.Ocean]: 0,
                [TileType.Port]: 0,
            }
        },
        name: "new"
    })
}
function deleteActiveTileGroup() {
    if (tileGroups.value.length <= 1)
        return

    const idx = tileGroups.value.findIndex(x => x.name == activeTileGroup.value.name)
    if (idx < 0) {
        activeTileGroup.value = tileGroups.value[0]
        return
    }
    tileGroups.value.splice(idx, 1)
    if (idx >= tileGroups.value.length)
        activeTileGroup.value = tileGroups.value[tileGroups.value.length - 1]
}



function makeScenario(): Scenario | undefined {
    if (maxAllowedCount.value == undefined || minAllowedCount.value == undefined)
        return undefined

    return {
        board: {
            robber: {
                type: robberPlacement.value
            },
            tileGroups: tileGroups.value.map(x => {
                return {
                    coordinates: {
                        method: GenerationMethod.SelectOne,
                        data: x.coordinates
                    },
                    portResources: undefined!,
                    resourceNumberAssignment: undefined!,
                    resources: undefined!,
                    tileTypes: x.tileTypes.method == GenerationMethod.Fixed ? {
                        method: GenerationMethod.Fixed,
                        data: x.tileTypes.fixed
                    } : {
                        method: GenerationMethod.Distribution,
                        data: x.tileTypes.distribution
                    }
                }
            })
        },
        players: {
            additionalStartingDevCards: [],
            additionalStartingHandCards: [],
            maxAllowedCount: maxAllowedCount.value,
            minAllowedCount: minAllowedCount.value
        },
        startingPhase: startingPhase.value,
        devCardStacks: defaultScenario.devCardStacks
    }
}
function copyJSONToClipboard() {
    const sc = makeScenario()
    navigator.clipboard.writeText(JSON.stringify(sc))
    console.log(sc)
}
</script>

<template>
    <h1>Custom Scenario</h1>
    <div class="middle">
        <SideMenu>            
            <InputGroup title="Players" :status="playersValid">
                <LabeledInput label="At least">
                    <IntegerInput 
                        :rules="[x => x == 0 ? 'At least one player' : true]"
                        min="1"
                        max="7"
                        v-model="minAllowedCount"
                    />
                </LabeledInput>
                <LabeledInput
                    label="At most">
                    <IntegerInput 
                        :rules="[x => x > 7 ? 'At most seven players' : true]"
                        min="1"
                        max="7"
                        v-model="maxAllowedCount"
                    />
                </LabeledInput>
            </InputGroup>
            <InputGroup title="Miscellaneous" :status="true">
                <LabeledInput label="Starting phase">
                    <select v-model="startingPhase">
                        <option :value="ScenarioStartingPhaseType.WithInitialPlacing">Initial placing</option>
                    </select>
                </LabeledInput>
                <LabeledInput
                    label="Robber at start">
                    <select v-model="robberPlacement">
                        <option :value="ScenarioRobberPlacement.RandomDesert">Random desert</option>
                    </select>
                </LabeledInput>
            </InputGroup>
            <label for="tile-groups-label" style="display: flex; flex-direction: row; justify-content: space-between;">
                <span>
                    Tile groups
                    <ErrorImg :status="tileGroupsValid"/>
                </span>
                <div>
                    <table class="tile-groups" aria-labelledby="tile-groups-label">
                        <tr
                            v-for="val of tileGroups"
                            @click="activeTileGroup = val"
                            @keypress.enter="activeTileGroup = val"
                            @keypress.space="activeTileGroup = val"
                            :class="activeTileGroup.name == val.name ? 'selected-table' : ''"
                            :aria-selected="activeTileGroup.name == val.name"
                            tabindex="0">
                            <td>
                                {{ val.name }}
                                <ErrorImg :status="tileGroupValid(val)"/>
                            </td>
                        </tr>
                    </table>
                    <span>
                        <button @click="appendEmptyTileGroup" type="button">
                            Add
                        </button>
                        
                        <button @click="deleteActiveTileGroup" type="button" :disabled="tileGroups.length <= 1">
                            Delete
                        </button>
                    </span>
                </div>
            </label>
            <ErrorText :status="scenarioValid ? true : 'There are still errors in the scenario'"/>
            <button @click="copyJSONToClipboard" :disabled="!scenarioValid">Copy as JSON</button>
        </SideMenu>
        <Container :tile-coordinates="tileGroups.flatMap(tg => tg.coordinates).flat()">
            <!-- first, draw all paths -->
            <g v-for="tg of tileGroups">
                <path                    
                    v-for="coord of tg.coordinates.flat()"
                    :d="tilePath(coord)"
                    fill="gray"
                    @click="activeCoord = coord; activeTileGroup = tg"
                />
            </g>
            <!-- draw highlighted tile group -->
            <path
                v-for="coord of activeTileGroup.coordinates.flat()"
                :d="tilePath(coord)"
                fill="green"
                @click="activeCoord = coord"
            />
            <!-- draw selected tile -->
            <path
                :d="tilePath(activeCoord)"
                stroke="red"
                stroke-width="7"
                fill="none"
            />
        </Container>
        <SideMenu>
            <Setting 
                name="Active tile group"
                :initial="activeTileGroup.name"
                :is-valid="x => x.length > 0" 
                :update="x => activeTileGroup.name = x"
                />

            <!-- providing count info -->
            <span v-if="activeTileGroupInfo.providingCount[0] == 0 && activeTileGroupInfo.providingCount[1] == 0"> Does not provide any tiles </span>
            <span v-else-if="activeTileGroupInfo.providingCount[0] == activeTileGroupInfo.providingCount[1]"> Provides {{ activeTileGroupInfo.providingCount[0] }} tiles</span>
            <span v-else> Provides between {{ activeTileGroupInfo.providingCount[0] }} and {{ activeTileGroupInfo.providingCount[1]}} tiles</span>

            <InputGroup 
                title="Tile type distribution" 
                :status="mostTiles(activeTileGroup.coordinates) > tileTypesCurrentLen(activeTileGroup.tileTypes)
                         ? `Too few tiles (provides ${tileTypesCurrentLen(activeTileGroup.tileTypes)} of ${mostTiles(activeTileGroup.coordinates)})` 
                         : true">
                <LabeledInput label="Method">
                    <select v-model="activeTileGroup.tileTypes.method">
                        <option :value="GenerationMethod.Distribution">Distribution</option>
                        <option :value="GenerationMethod.Fixed">Fixed</option>
                    </select>
                </LabeledInput>
                <div v-if="activeTileGroup.tileTypes.method == GenerationMethod.Distribution">
                    <LabeledInput label="Ocean">
                        <input type="number" min="0"
                            v-model="activeTileGroup.tileTypes.distribution[TileType.Ocean]"
                        />
                    </LabeledInput>
                    <LabeledInput label="Port">
                        <input type="number" min="0"
                            v-model="activeTileGroup.tileTypes.distribution[TileType.Port]"
                        />
                    </LabeledInput>
                    <LabeledInput label="Desert">
                        <input type="number" min="0"
                            v-model="activeTileGroup.tileTypes.distribution[TileType.Desert]"
                        />
                    </LabeledInput>
                    <LabeledInput label="Resource">
                        <input type="number" min="0"
                            v-model="activeTileGroup.tileTypes.distribution[TileType.Resource]"
                        />
                    </LabeledInput>
                </div>
                <div v-if="activeTileGroup.tileTypes.method == GenerationMethod.Fixed">
                    <FixedSelectionList 
                        :keys="[TileType.Ocean, TileType.Port, TileType.Desert, TileType.Resource]"
                        :strings="x => TileType[x]"
                        v-model="activeTileGroup.tileTypes.fixed"
                        :highlight-idx="activeTileGroup.coordinates.length != 1 ? undefined 
                                        : activeTileGroup.coordinates[0].findIndex(x => sameCoordinate(x, activeCoord))"/>
                </div>
            </InputGroup>

            <hr/>

            <!-- tile type distribution -->
            <h4>Active coordinate: ({{ activeCoord[0] }}, {{ activeCoord[1] }})</h4>
            <span>Provided by: {{ activeCoordInfo.providingGroups.map(x => x.name).join(', ') }}</span>
        </SideMenu>
    </div>
</template>

<style scoped>
@import '../assets/base.css';


.middle {
    width: calc(max(var(--wide-area-width), var(--default-area-width)));
    display: flex;
    flex-direction: row;
}

.middle > :first-child, .middle > :last-child {
    max-width: 30%;
    height: max-content;
}

.tile-groups {
    background-color: white;
    width: 100%;
    text-align: end;
}

.selected-table {
    background-color: rgb(231, 231, 231);
}
.selected-coordinate {
    stroke-width: 7px;
    stroke: red;
    pointer-events: none;
    z-index: 5;
}

input, select {
    margin-left: 1em;
}

select {
    min-width: 9em;
}

svg {
    padding: 20px;
    max-height: 70vh;
}

fieldset > *:not(:first-child) {
    margin-top: 5px;
}
</style>