<script setup lang="ts">
import Container from '@/game-components/board/Container.vue';
import { tilePath } from '@/game-components/board/Layout';
import SideMenu from '@/misc/SideMenu.vue';
import LabeledInput from '@/modals/input-fields/LabeledInput.vue';
import { type Coordinate, defaultScenario, GenerationMethod, sameCoordinate, type Scenario, ScenarioRobberPlacement, ScenarioStartingPhaseType } from 'shared';
import { unfreeze, type UnFreeze } from 'structurajs';
import { computed, ref, toRaw, watch } from 'vue';

const scenario = ref<UnFreeze<Scenario>>(unfreeze(structuredClone(defaultScenario)))
const activeTileGroup = ref(0)
const activeTileGroupInfo = computed(() => {
    const tg = scenario.value.board.tileGroups[activeTileGroup.value]

    // Providing count refers to the number of tiles generated by this tile group
    // specified by the lower and upper bound
    let providingCount: [number, number]
    if (tg.coordinates.data.length == 0)
        providingCount = [0, 0]
    else
        providingCount = [tg.coordinates.data.map(x => x.length).sort()[0], tg.coordinates.data.map(x => x.length).sort()[tg.coordinates.data.length - 1]]

    return { providingCount }
})
const activeCoord = ref<Coordinate>(scenario.value.board.tileGroups[activeTileGroup.value].coordinates.data[0][0])
const activeCoordInfo = computed(() => {
    const providingGroups = scenario.value.board.tileGroups.reduce<number[]>((s, tg, i) => tg.coordinates.data.some(arr => arr.some(x => sameCoordinate(x, activeCoord.value))) ? [i + 1, ...s] : s, [])
    return { providingGroups }
})

watch(scenario, () => {

}, { deep: true })

function appendEmptyTileGroup() {
    scenario.value.board.tileGroups.push({
        coordinates: {
            method: GenerationMethod.SelectOne,
            data: [[]]
        },
        portResources: {
            method: GenerationMethod.Fixed,
            data: []
        },
        resourceNumberAssignment: [],
        resources: {
            method: GenerationMethod.Fixed,
            data: [],
        },
        tileTypes: {
            method: GenerationMethod.Fixed,
            data: []
        }
    })
}
function deleteActiveTileGroup() {
    if (scenario.value.board.tileGroups.length <= 1)
        return

    scenario.value.board.tileGroups.splice(activeTileGroup.value, 1)
    if (activeTileGroup.value >= scenario.value.board.tileGroups.length)
        activeTileGroup.value = scenario.value.board.tileGroups.length - 1
}


function copyJSONToClipboard() {
    navigator.clipboard.writeText(JSON.stringify(toRaw(scenario.value)))
    console.log(scenario.value)
}

function restrictToInteger(t: HTMLInputElement) {
    t.value = t.value.replace(/[^0-9]/g, '')
    if (t.value == '' || t.valueAsNumber == 0) t.value = '1'
    if (t.valueAsNumber > 7) t.value = '7'

    return t.valueAsNumber
}
</script>

<template>
    <h1>Custom Scenario</h1>
    <div class="middle">
        <SideMenu>
            <h4>Players</h4>
            <LabeledInput
                label="Minimal player count">
                <input
                    type="number"
                    min="1"
                    max="7"
                    step="1"
                    v-model.number="scenario.players.minAllowedCount"
                    required
                    @input="e => {
                        const val = restrictToInteger(e.target as HTMLInputElement)

                        if (val > scenario.players.maxAllowedCount)
                            scenario.players.maxAllowedCount = val
                    }"
                />
            </LabeledInput>
            <LabeledInput
                label="Maximal player count">
                <input
                    type="number"
                    min="1"
                    max="7"
                    step="1"
                    v-model.number="scenario.players.maxAllowedCount"
                    required
                    @input="e => {
                        const t = (e.target as HTMLInputElement)
                        t.value = t.value.replace(/[^0-9]/g, '')
                        if (t.value == '' || t.valueAsNumber == 0) t.value = '1'
                        if (t.valueAsNumber > 7) t.value = '7'

                        if (t.valueAsNumber < scenario.players.minAllowedCount)
                            scenario.players.minAllowedCount = t.valueAsNumber
                    }"
                />
            </LabeledInput>
            <h4>Board</h4>
            <LabeledInput label="Tile groups" for="tile-groups-label">
                <div>
                    <table class="tile-groups" aria-labelledby="tile-groups-label" aria->
                        <tr
                            v-for="idx in new Array(scenario.board.tileGroups.length).keys()"
                            @click="activeTileGroup = idx"
                            @keypress.enter="activeTileGroup = idx"
                            @keypress.space="activeTileGroup = idx"
                            :class="activeTileGroup == idx ? 'selected-table' : ''"
                            :aria-selected="activeTileGroup == idx"
                            tabindex="0">
                            <td>
                                Group {{ idx + 1}}
                            </td>
                        </tr>
                    </table>
                    <span>
                        <button @click="appendEmptyTileGroup" type="button">
                            Add
                        </button>
                        
                        <button @click="deleteActiveTileGroup" type="button" :disabled="scenario.board.tileGroups.length <= 1">
                            Delete
                        </button>
                    </span>
                </div>
            </LabeledInput>
            <LabeledInput
                label="Robber at start">
                <label>
                    <input
                        type="radio"
                        v-model="scenario.board.robber.type"
                        required
                        :value="ScenarioRobberPlacement.RandomDesert"
                    />
                    Random desert
                </label>
            </LabeledInput>

            <h4>Miscellaneous</h4>
            <LabeledInput
                label="Starting phase">
                <label>
                    <input
                        type="radio"
                        v-model="scenario.startingPhase"
                        required
                        :value="ScenarioStartingPhaseType.WithInitialPlacing"
                    />
                    With initial placing
                </label>
            </LabeledInput>
            <button @click="copyJSONToClipboard">Copy as JSON</button>
        </SideMenu>
        <Container :tile-coordinates="scenario.board.tileGroups.flatMap(tg => tg.coordinates.data).flat()">
            <!-- first, draw all paths -->
            <g v-for="[i, tg] of scenario.board.tileGroups.entries()">
                <path                    
                    v-for="coord of tg.coordinates.data.flat()"
                    :d="tilePath(coord)"
                    fill="gray"
                    @click="activeCoord = coord; activeTileGroup = i"
                />
            </g>
            <!-- draw highlighted tile group -->
            <path
                v-for="coord of scenario.board.tileGroups[activeTileGroup].coordinates.data.flat()"
                :d="tilePath(coord)"
                fill="green"
                @click="activeCoord = coord"
            />
            <!-- draw selected tile -->
            <path
                :d="tilePath(activeCoord)"
                stroke="red"
                stroke-width="7"
                fill="none"
            />
        </Container>
        <SideMenu>
            <h4>Active tile group: Group {{ activeTileGroup + 1}}</h4>

            <!-- providing count info -->
            <span v-if="activeTileGroupInfo.providingCount[0] == 0 && activeTileGroupInfo.providingCount[1] == 0"> Does not provide any tiles </span>
            <span v-else-if="activeTileGroupInfo.providingCount[0] == activeTileGroupInfo.providingCount[1]"> Provides {{ activeTileGroupInfo.providingCount[0] }} tiles</span>
            <span v-else> Provides between {{ activeTileGroupInfo.providingCount[0] }} and {{ activeTileGroupInfo.providingCount[1]}} tiles</span>

            <fieldset>
                <legend>Tile type distribution</legend>
                <LabeledInput label="Method">
                    <label>
                        <input
                            type="radio"
                            v-model="scenario.board.tileGroups[activeTileGroup].tileTypes.method"
                            :value="GenerationMethod.Distribution"
                        />
                        Distributed
                    </label>
                    <label>
                        <input
                            type="radio"
                            v-model="scenario.board.tileGroups[activeTileGroup].tileTypes.method"
                            :value="GenerationMethod.Fixed"
                            @change="e => console.log(e)"
                        />
                        Fixed
                    </label>
                </LabeledInput>
                <div v-if="scenario.board.tileGroups[activeTileGroup].tileTypes.method == GenerationMethod.Distribution">
                    <LabeledInput label="Ocean">
                        <input type="number"
                            v-model="scenario.board.tileGroups[activeTileGroup].tileTypes.data"
                            @input="e => restrictToInteger(e.target as HTMLInputElement)"
                        />
                    </LabeledInput>
                </div>
            </fieldset>
            <!-- tile type distribution -->
            <h4>Active coordinate: ({{ activeCoord[0] }}, {{ activeCoord[1] }})</h4>
            <span>Provided by groups: {{ activeCoordInfo.providingGroups.join(', ') }}</span>
        </SideMenu>
    </div>
</template>

<style scoped>
@import '../assets/base.css';


.middle {
    width: var(--wide-area-width);
    display: flex;
    flex-direction: row;
}

.tile-groups {
    background-color: white;
    width: 100%;
    text-align: end;
}

.selected-table {
    background-color: rgb(231, 231, 231);
}
.selected-coordinate {
    stroke-width: 7px;
    stroke: red;
    pointer-events: none;
    z-index: 5;
}
</style>